<?php

/**
 * @file
 * The module file.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\views_exclude_previous\EntityRenderHistory;

/**
 * Implements hook_entity_build_defaults_alter().
 */
function views_exclude_previous_entity_build_defaults_alter(array &$build, EntityInterface $entity, $view_mode) {
  // Note that we use hook_entity_build_defaults_alter() as this runs even
  // when the entity is in render cache.
  $render_history = \Drupal::service('views_exclude_previous.render_history');
  assert($render_history instanceof EntityRenderHistory);
  $render_history->add($entity);
}
